### ISSUE TITLE
Downgrade to 4.5 from 4.5.1

### ISSUE THREAD

**Issue by schungx** [mikegore1000/SqueezeMe#5]
Hi Mike, is it possible for you to downgrade the NuGet package to 4.5 instead of 4.5.1?  As you know, Azure doesn't support 4.5.1 so it get troublesome.  Thanks!

**Comment by schungx** [comment]
Hi, any news on this?

**Comment by mikegore1000** [comment]
Hi,

Sorry I haven't been able to look at this sooner.  Just pushed out a new version to nuget.org.  The version to use is 1.2.31.  Ignore the 1.1.30 version.

**Comment by schungx** [comment]
OK great!
- Stephen
