### ISSUE TITLE
Chaining Middleware

### ISSUE THREAD

**Issue by secovel** [mikegore1000/SqueezeMe#6]
UseCompression should return IAppBuilder so that further middleware can be chained.  Right now it returns void so this is not possible:

appBuilder.Use<GlobalExceptionMiddleware>().UseCompression().UseWebApi(config);

Also, what license are you using?

Thanks.

**Comment by mikegore1000** [comment]
Hi.  I've just added a license file to the repository (MIT).

I should be able to look at fixing this issue later today.

**Comment by mikegore1000** [comment]
Just sorted this out.  Will update the issue once the CI server has pushed to nuget.org.

**Comment by mikegore1000** [comment]
This has just been pushed to nuget.org. Version 1.3.33.

**Comment by secovel** [comment]
Wow, that was fast!  Thanks.
